version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  go-test:
    docker:
      - image: cimg/go:1.18.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: installing dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: run testing codes
          command: go test -race -coverprofile=coverage.out -covermode=atomic
      - codecov/upload:
          file: coverage.out

workflows:
  build-updates:
    jobs:
      - go-test
